#
# This file is autogenerated during plugin quickstart and overwritten during
# plugin makedist. DO NOT CHANGE IT if you plan to use plugin makedist to update 
# the distribution.
#

from setuptools import setup, find_packages

kwargs = {'author': '',
 'author_email': '',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': "'OpenMDAO drivers using DAKOTA (Design Analysis Kit for Optimization and Terascale Applications)'",
 'download_url': '',
 'entry_points': '[openmdao.component]\ndakota_driver.driver.DakotaOptimizer=dakota_driver.driver:DakotaOptimizer\ndakota_driver.driver.DakotaVectorStudy=dakota_driver.driver:DakotaVectorStudy\ndakota_driver.driver.DakotaMultidimStudy=dakota_driver.driver:DakotaMultidimStudy\n\n[openmdao.driver]\ndakota_driver.driver.DakotaOptimizer=dakota_driver.driver:DakotaOptimizer\ndakota_driver.driver.DakotaVectorStudy=dakota_driver.driver:DakotaVectorStudy\ndakota_driver.driver.DakotaMultidimStudy=dakota_driver.driver:DakotaMultidimStudy\n\n[openmdao.container]\ndakota_driver.driver.DakotaOptimizer=dakota_driver.driver:DakotaOptimizer\ndakota_driver.driver.DakotaVectorStudy=dakota_driver.driver:DakotaVectorStudy\ndakota_driver.driver.DakotaMultidimStudy=dakota_driver.driver:DakotaMultidimStudy',
 'include_package_data': True,
 'install_requires': ['openmdao.main', 'pyDAKOTA'],
 'keywords': ['openmdao'],
 'license': 'Apache License, Version 2.0',
 'maintainer': '',
 'maintainer_email': '',
 'name': 'dakota_driver',
 'package_data': {'dakota_driver': []},
 'package_dir': {'': 'src'},
 'packages': ['dakota_driver'],
 'url': 'https://github.com/OpenMDAO-Plugins/dakota_driver',
 'version': '0.1',
 'zip_safe': False}


setup(**kwargs)

